services:
  frontend:
    container_name: frontend
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - webproxy

networks:
  webproxy:
    external: true