name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH and Git Pull
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/shitshatui

            echo "Pulling updates..."
            git pull origin main

            echo "Stopping current containers..."
            docker compose down

            echo "Rebuilding and starting containers..."
            docker compose up --build -d

            echo "Cleaning up older images (>12h)..."
            docker image prune -a -f --filter "until=12h"
